[project]
name = "model"
version = "0.1.0"
description = "LLaMA model optimization"
requires-python = ">=3.9"
dependencies = [
    "torch>=1.13.0",
    "transformers>=4.35.0",
    "accelerate>=0.20.0",
    "numpy<2.0.0",
    "safetensors",
    "huggingface-hub",
    "auto-gptq"
]
